### ISSUE TITLE
Env variable name for udp sender host

### ISSUE THREAD

**Issue by CatalinMustata** [opentracing-contrib/java-spring-jaeger#115]
While it seems relatively clear from the documentation, I can't seem to get the client to send spans to the host when deployed in Kubernetes (works just fine locally)

I'm thinking I don't have the proper var name, but any suggestion would be highly appreciated:

When building the docker image for my app, I'm using the following entrypoint:
```
ENTRYPOINT ["java", \
            "-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector", \
            "-DOPENTRACING_JAEGER_UDP_SENDER_HOST=$JAEGER_HOST", \
            "-jar", \
            "app.jar"]
```

When deploying to Kubernetes, I'm using the same strategy I used for the NodeJS apps I deployed, adding this to the container specs:
```
         env:
            - name: JAEGER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```

Any pointers on debugging this would be very helpful.
