### ISSUE TITLE
Remote Controller Sampler should have separate configuration fields for host and port

### ISSUE THREAD

**Issue by backjo** [opentracing-contrib/java-spring-jaeger#52]
On our K8s clusters, we set up Jaeger-Agent as a DaemonSet. This means that we get the IP address of the agent the following way:
```yaml
- name: OPENTRACING_JAEGER_UDPSENDER_HOST
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
```

This allows us to inject the hostname fine, which works great for configuring the UdpSender - but it's not easy to inject a combination hostname + port this way, which makes it hard to configure remote sampling. Having separate properties for these two fields would make this kind of use case easier.
